const lightPalette = {
  primary: "#0A0A0A",
  secondary: "#EDE8DF",
  accent: "#B4CEE7",
  background: "#FAF9F4",
  surface: "#f4f2ed",
  textPrimary: "#1a1a1a",
  textSecondary: "#6b6b6b",
  border: "#E0DAD1",
  success: "#22c55e",
  error: "#ef4444",
  warning: "#f59e0b",
  disabled: "#BCB6AE",
};
const darkPalette = {
  primary: "#FEFEFE",
  secondary: "#141414",
  accent: "#C8DDF0",
  background: "#0A0A0A",
  surface: "#141414",
  textPrimary: "#FEFEFE",
  textSecondary: "#ACABA9",
  border: "#2D2D2D",
  success: "#4ade80",
  error: "#f87171",
  warning: "#fbbf24",
  disabled: "#6A6560",
};
const createTheme = (palette, config) => ({
  ...palette,
  textDisabled: palette.disabled,
  accentMuted: palette.secondary,
  ...config,
});
export const lightTheme = createTheme(lightPalette, {
  primaryForeground: "#FFFFFF",
  secondaryForeground: "#0A0A0A",
  accentForeground: "#0A0A0A",
  surfaceElevated: "#FFFFFF",
  surfaceMuted: "#EDE8DF",
  chatBackground: "#E7E1D7",
  borderMuted: "#E8E2D9",
  danger: lightPalette.error,
  dangerBorder: "#ffbfbf",
  dangerMuted: "#FFEBEA",
  successMuted: "#F0FDF4",
  warningMuted: "#FFFBEB",
  bubble: {
    outgoing: "#B4CEE7",
    outgoingText: "#0A0A0A",
    incoming: "#FFFFFF",
    incomingText: "#0A0A0A",
    incomingBorder: "#E0DAD1",
  },
  online: lightPalette.success,
  typing: lightPalette.textSecondary,
  overlay: "rgba(37, 33, 30, 0.28)",
  inputBackground: "#FFFFFF",
  tabBar: "#FAF9F4",
  tabBarActive: "#0A0A0A",
  tabBarInactive: lightPalette.textSecondary,
  headerBackground: "#FAF9F4",
  statusBarStyle: "dark",
  primaryText: "#FAF9F4",
});
export const darkTheme = createTheme(darkPalette, {
  primaryForeground: "#0A0A0A",
  secondaryForeground: "#FAF9F4",
  accentForeground: "#0A0A0A",
  surfaceElevated: "#3A3633",
  surfaceMuted: "#141414",
  chatBackground: "#1C1917",
  borderMuted: "#312D2A",
  danger: darkPalette.error,
  dangerBorder: "#6C1E1B",
  dangerMuted: "#2F1517",
  successMuted: "#052E16",
  warningMuted: "#2A2209",
  bubble: {
    outgoing: "#C8DDF0",
    outgoingText: "#0A0A0A",
    incoming: "#141414",
    incomingText: "#FAF9F4",
    incomingBorder: "#222126",
  },
  online: darkPalette.success,
  typing: darkPalette.textSecondary,
  overlay: "rgba(0, 0, 0, 0.56)",
  inputBackground: "#141414",
  tabBar: "#0A0A0A",
  tabBarActive: "#F2F2F2",
  tabBarInactive: darkPalette.textSecondary,
  headerBackground: "#0A0A0A",
  statusBarStyle: "light",
  primaryText: "#0A0A0A",
});
