export const extractedLightPalette = {
    primary: '#101010',
    secondary: '#EDE8DF',
    accent: '#B4CEE7',
    background: '#FAF9F4',
    surface: '#FFFFFF',
    textPrimary: '#101010',
    textSecondary: '#7A736A',
    border: '#E0DAD1',
    success: '#22c55e',
    error: '#ef4444',
    warning: '#f59e0b',
    disabled: '#BCB6AE',
};
export const extractedDarkPalette = {
    primary: '#FEFEFE',
    secondary: '#1A1A1A',
    accent: '#C8DDF0',
    background: '#101010',
    surface: '#1A1A1A',
    textPrimary: '#FEFEFE',
    textSecondary: '#AEAEAE',
    border: '#333333',
    success: '#4ade80',
    error: '#f87171',
    warning: '#fbbf24',
    disabled: '#6A6560',
};
export const extractedPalette = {
    light: extractedLightPalette,
    dark: extractedDarkPalette,
};
export const lightTheme = {
    ...extractedLightPalette,
    primaryForeground: '#FFFFFF',
    secondaryForeground: '#101010',
    accentForeground: '#101010',
    surfaceElevated: '#FFFFFF',
    surfaceMuted: '#EDE8DF',
    chatBackground: '#E7E1D7',
    borderMuted: '#E8E2D9',
    danger: extractedLightPalette.error,
    dangerMuted: '#FEF2F2',
    successMuted: '#F0FDF4',
    warningMuted: '#FFFBEB',
    bubble: {
        outgoing: '#B4CEE7',
        outgoingText: '#101010',
        incoming: '#FFFFFF',
        incomingText: '#101010',
        incomingBorder: '#E0DAD1',
    },
    online: extractedLightPalette.success,
    typing: extractedLightPalette.textSecondary,
    overlay: 'rgba(37, 33, 30, 0.28)',
    inputBackground: '#FFFFFF',
    tabBar: '#FAF9F4',
    tabBarActive: '#FD5C08',
    tabBarInactive: '#BCB6AE',
    headerBackground: '#FAF9F4',
    statusBarStyle: 'dark',
};
export const darkTheme = {
    ...extractedDarkPalette,
    primaryForeground: '#101010',
    secondaryForeground: '#FAF9F4',
    accentForeground: '#101010',
    surfaceElevated: '#3A3633',
    surfaceMuted: '#1A1A1A',
    chatBackground: '#1C1917',
    borderMuted: '#312D2A',
    danger: extractedDarkPalette.error,
    dangerMuted: '#2F1517',
    successMuted: '#052E16',
    warningMuted: '#2A2209',
    bubble: {
        outgoing: '#C8DDF0',
        outgoingText: '#101010',
        incoming: '#1A1A1A',
        incomingText: '#FAF9F4',
        incomingBorder: '#222126',
    },
    online: extractedDarkPalette.success,
    typing: extractedDarkPalette.textSecondary,
    overlay: 'rgba(0, 0, 0, 0.56)',
    inputBackground: '#1A1A1A',
    tabBar: '#101010',
    tabBarActive: '#FD5C08',
    tabBarInactive: '#6A6560',
    headerBackground: '#101010',
    statusBarStyle: 'light',
};
