export const lightColors = {
  background: '#f6f8fa',
  surface: '#ffffff',
  surfaceElevated: '#ffffff',
  surfaceMuted: '#f6f8fa',
  textPrimary: '#24292f',
  textSecondary: '#57606a',
  textDisabled: '#8c959f',
  accent: '#0969da',
  accentMuted: '#ddf4ff',
  accentForeground: '#ffffff',
  border: '#d0d7de',
  borderMuted: '#eaeef2',
  danger: '#cf222e',
  dangerMuted: '#FFEBE9',
  success: '#1a7f37',
  successMuted: '#dafbe1',
  warning: '#9a6700',
  warningMuted: '#fff8c5',
  bubble: {
    outgoing: '#0969da',
    outgoingText: '#ffffff',
    incoming: '#ffffff',
    incomingText: '#24292f',
    incomingBorder: '#d0d7de',
  },
  online: '#1a7f37',
  typing: '#0969da',
  overlay: 'rgba(0,0,0,0.5)',
  inputBackground: '#ffffff',
  tabBar: '#ffffff',
  tabBarActive: '#0969da',
  tabBarInactive: '#8c959f',
  headerBackground: '#ffffff',
  statusBarStyle: 'dark' as 'light' | 'dark',
}

export const darkColors = {
  background: '#0d1117',
  surface: '#161b22',
  surfaceElevated: '#21262d',
  surfaceMuted: '#161b22',
  textPrimary: '#c9d1d9',
  textSecondary: '#8b949e',
  textDisabled: '#484f58',
  accent: '#58a6ff',
  accentMuted: '#0d2149',
  accentForeground: '#ffffff',
  border: '#30363d',
  borderMuted: '#21262d',
  danger: '#f85149',
  dangerMuted: '#490202',
  success: '#3fb950',
  successMuted: '#0f2d1a',
  warning: '#d29922',
  warningMuted: '#2d1f00',
  bubble: {
    outgoing: '#1f6feb',
    outgoingText: '#ffffff',
    incoming: '#21262d',
    incomingText: '#c9d1d9',
    incomingBorder: '#30363d',
  },
  online: '#3fb950',
  typing: '#58a6ff',
  overlay: 'rgba(0,0,0,0.7)',
  inputBackground: '#0d1117',
  tabBar: '#161b22',
  tabBarActive: '#58a6ff',
  tabBarInactive: '#484f58',
  headerBackground: '#161b22',
  statusBarStyle: 'light' as 'light' | 'dark',
}

export type ColorTokens = typeof lightColors

export const typography = {
  fontFamily: {
    regular: 'Geist-Regular',
    medium: 'Geist-Medium',
    semiBold: 'Geist-SemiBold',
    bold: 'Geist-Bold',
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 30,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semiBold: '600' as const,
    bold: '700' as const,
  },
  lineHeight: {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.75,
  },
}

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
  huge: 48,
}

export const borderRadius = {
  sm: 6,
  md: 12,
  lg: 20,
  pill: 999,
}

export const shadows = {
  sm: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  xl: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 10,
  },
}
