export const lightColors = {
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceElevated: '#FFFFFF',
  surfaceMuted: '#F2F2F7',
  chatBackground: '#ECE5DD',
  textPrimary: '#000000',
  textSecondary: '#8E8E93',
  textDisabled: '#C7C7CC',
  accent: '#007AFF',
  accentMuted: '#E5F1FF',
  accentForeground: '#FFFFFF',
  border: '#C6C6C8',
  borderMuted: '#E5E5EA',
  danger: '#FF3B30',
  dangerMuted: '#FFEBE9',
  success: '#34C759',
  successMuted: '#DAFBE1',
  warning: '#FF9500',
  warningMuted: '#FFF3CD',
  bubble: {
    outgoing: '#007AFF',
    outgoingText: '#FFFFFF',
    incoming: '#FFFFFF',
    incomingText: '#000000',
    incomingBorder: 'transparent',
  },
  online: '#34C759',
  typing: '#8E8E93',
  overlay: 'rgba(0,0,0,0.4)',
  inputBackground: '#F2F2F7',
  tabBar: '#F9F9F9',
  tabBarActive: '#007AFF',
  tabBarInactive: '#8E8E93',
  headerBackground: '#FFFFFF',
  statusBarStyle: 'dark' as 'light' | 'dark',
}

export const darkColors = {
  background: '#000000',
  surface: '#1C1C1E',
  surfaceElevated: '#2C2C2E',
  surfaceMuted: '#1C1C1E',
  chatBackground: '#0B141A',
  textPrimary: '#FFFFFF',
  textSecondary: '#8E8E93',
  textDisabled: '#48484A',
  accent: '#0A84FF',
  accentMuted: '#0A2040',
  accentForeground: '#FFFFFF',
  border: '#38383A',
  borderMuted: '#2C2C2E',
  danger: '#FF453A',
  dangerMuted: '#3D0C0A',
  success: '#30D158',
  successMuted: '#0D2B13',
  warning: '#FF9F0A',
  warningMuted: '#2D1F00',
  bubble: {
    outgoing: '#0A84FF',
    outgoingText: '#FFFFFF',
    incoming: '#1C1C1E',
    incomingText: '#FFFFFF',
    incomingBorder: 'transparent',
  },
  online: '#30D158',
  typing: '#8E8E93',
  overlay: 'rgba(0,0,0,0.6)',
  inputBackground: '#1C1C1E',
  tabBar: '#000000',
  tabBarActive: '#0A84FF',
  tabBarInactive: '#48484A',
  headerBackground: '#000000',
  statusBarStyle: 'light' as 'light' | 'dark',
}

export type ColorTokens = typeof lightColors

export const typography = {
  fontFamily: {
    regular: 'Geist-Regular',
    medium: 'Geist-Medium',
    semiBold: 'Geist-SemiBold',
    bold: 'Geist-Bold',
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 30,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semiBold: '600' as const,
    bold: '700' as const,
  },
  lineHeight: {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.75,
  },
}

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
  huge: 48,
}

export const borderRadius = {
  sm: 6,
  md: 12,
  lg: 20,
  pill: 999,
}

export const shadows = {
  sm: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  xl: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 10,
  },
}
