const sharedCommon = {
    send: 'Send',
    cancel: 'Cancel',
    delete: 'Delete',
    copy: 'Copy',
    reply: 'Reply',
    loading: 'Loading...',
    error: 'Something went wrong.',
    retry: 'Retry',
    ok: 'OK',
    confirm: 'Confirm',
};
export const Strings = {
    app: {
        name: 'Shaik',
        tagline: 'Encrypted P2P Chat',
    },
    chat: {
        placeholder: 'Message...',
        today: 'Today',
        yesterday: 'Yesterday',
        newMessages: 'New Messages',
        newMessagePill: 'New message ↓',
        connecting: 'Connecting...',
        online: 'Online',
        lastSeenPrefix: 'Last seen ',
        webrtcWarning: 'WebRTC unavailable in Expo Go. Use a dev build for messaging.',
        typingIndicator: (name) => `${name} is typing...`,
        emptyChat: 'No messages yet',
        emptyChatSub: 'Messages are end-to-end encrypted.',
    },
    chatList: {
        title: 'Messages',
        searchPlaceholder: 'Search conversations...',
        noResults: (q) => `No conversations matching "${q}"`,
        emptyTitle: 'No conversations yet',
        emptySub: 'Add a contact and start your first secure, encrypted conversation.',
        newMessage: 'New Message',
        justNow: 'just now',
    },
    contacts: {
        title: 'Contacts',
        searchPlaceholder: 'Search contacts...',
        emptyTitle: 'No contacts yet',
        emptySub: 'Add people using their phone number.',
        addContact: 'Add Contact',
        noResults: 'No contacts found',
    },
    settings: {
        title: 'Settings',
        profile: 'Profile',
        displayName: 'Display Name',
        phoneNumber: 'Phone Number',
        appearance: 'Appearance',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
        notifications: 'Notifications',
        enableNotifications: 'Enable Notifications',
        messagePreview: 'Message Preview',
        storage: 'Storage',
        clearCache: 'Clear Message Cache',
        clearCacheConfirm: 'This will delete all local message history. This action cannot be undone.',
        clearCacheConfirmBtn: 'Clear',
        cancel: sharedCommon.cancel,
        about: 'About',
        version: 'Version',
        licenses: 'Open Source Licenses',
    },
    common: {
        ...sharedCommon,
    },
    attachments: {
        camera: 'Camera',
        photoLibrary: 'Photo Library',
        document: 'Document',
        audio: 'Audio',
        remove: 'Remove',
    },
};
