import { cn } from "@/lib/utils";
import * as React from "react";
import { Text, View } from "react-native";
import { CARD_CLASSES } from "./styleTokens";
const Card = React.forwardRef(({ className, ...props }, ref) => (<View ref={ref} className={cn(CARD_CLASSES.root, className)} {...props}/>));
Card.displayName = "Card";
const CardHeader = React.forwardRef(({ className, ...props }, ref) => (<View ref={ref} className={cn(CARD_CLASSES.header, className)} {...props}/>));
CardHeader.displayName = "CardHeader";
const CardTitle = React.forwardRef(({ className, ...props }, ref) => (<Text ref={ref} className={cn(CARD_CLASSES.title, className)} {...props}/>));
CardTitle.displayName = "CardTitle";
const CardDescription = React.forwardRef(({ className, ...props }, ref) => (<Text ref={ref} className={cn(CARD_CLASSES.description, className)} {...props}/>));
CardDescription.displayName = "CardDescription";
const CardContent = React.forwardRef(({ className, ...props }, ref) => (<View ref={ref} className={cn(CARD_CLASSES.content, className)} {...props}/>));
CardContent.displayName = "CardContent";
const CardFooter = React.forwardRef(({ className, ...props }, ref) => (<View ref={ref} className={cn(CARD_CLASSES.footer, className)} {...props}/>));
CardFooter.displayName = "CardFooter";
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle };
