import * as React from "react";
import { Text as RNText } from "react-native";
import { cn } from "@/lib/utils";
import { TYPOGRAPHY_CLASSES } from "./styleTokens";
const H1 = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.h1, className)} {...props}/>));
H1.displayName = "H1";
const H2 = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.h2, className)} {...props}/>));
H2.displayName = "H2";
const H3 = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.h3, className)} {...props}/>));
H3.displayName = "H3";
const H4 = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.h4, className)} {...props}/>));
H4.displayName = "H4";
const P = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.p, className)} {...props}/>));
P.displayName = "P";
const Lead = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.lead, className)} {...props}/>));
Lead.displayName = "Lead";
const Muted = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.muted, className)} {...props}/>));
Muted.displayName = "Muted";
const Small = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.small, className)} {...props}/>));
Small.displayName = "Small";
const Code = React.forwardRef(({ className, ...props }, ref) => (<RNText ref={ref} className={cn(TYPOGRAPHY_CLASSES.code, className)} {...props}/>));
Code.displayName = "Code";
export { H1, H2, H3, H4, P, Lead, Muted, Small, Code };
